export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT' as const;
export const REMOVE_CONSTRUCTOR_INGREDIENT = 'REMOVE_CONSTRUCTOR_INGREDIENT' as const;
export const RESET_CONSTRUCTOR_INGREDIENTS = 'RESET_CONSTRUCTOR_INGREDIENTS' as const;
export const UPDATE_CONSTRUCTOR_INGREDIENTS = 'UPDATE_CONSTRUCTOR_INGREDIENTS' as const;
